name: Deploy React App to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      # 1. Clonează repository-ul
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Construiește imaginea Docker cu variabila de mediu
      - name: Build Docker image
        run: |
          docker build --build-arg VITE_API_URL=http://antonio-dev.go.ro/etf-predictor-be -t react-app:latest .

      # 3. Salvează și transferă imaginea pe Raspberry Pi
      - name: Save and transfer image to Raspberry Pi
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          docker save react-app:latest -o react-app.tar
          scp -i ~/.ssh/id_rsa -P 15621 react-app.tar antonio@antonio-dev.go.ro:/home/antonio/

      # 4. Încarcă imaginea și pornește containerul pe Raspberry Pi
      - name: Load image and deploy on Raspberry Pi
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i ~/.ssh/id_rsa -p 15621 antonio@antonio-dev.go.ro "
             docker load -i /home/antonio/react-app.tar &&
             docker stop react-app || true &&
             docker rm react-app || true &&
             docker run -d --name react-app -p 8081:80 react-app:latest
          "

      # 5. Curăță fișierele temporare de pe Raspberry Pi
      - name: Clean up Docker images and tar files on Raspberry Pi
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i ~/.ssh/id_rsa -p 15621 antonio@antonio-dev.go.ro "
             rm /home/antonio/react-app.tar
          "
